### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by lior007** [lllyasviel/IC-Light#101]
Traceback (most recent call last):
  File "D:\GITHUB\IC-Light\gradio_demo.py", line 10, in <module>
    from diffusers import StableDiffusionPipeline, StableDiffusionImg2ImgPipeline
  File "C:\Users\LIOR0\miniconda3\envs\iclight\lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "C:\Users\LIOR0\miniconda3\envs\iclight\lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "C:\Users\LIOR0\miniconda3\envs\iclight\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\Users\LIOR0\miniconda3\envs\iclight\lib\site-packages\huggingface_hub\__init__.py)

**Comment by lior007** [comment]
i fix it by:
pip install --upgrade torch transformers diffusers huggingface_hub

**Comment by Ted-cuchuan** [comment]
Well thanks!!! I got the same problem with you. Your solution is really useful.

**Comment by ngocdaothanh** [comment]
> pip install --upgrade torch transformers diffusers huggingface_hub

Thanks, this solution together with https://github.com/lllyasviel/IC-Light/issues/102 (gradio-3.48.0 gradio-client-0.6.1) work for me.

I'm using Python 3.10.16 on Pop OS and:

```
commit a77f2cdc5286eacfd82af2c01dadb6dbe8082750 (HEAD -> main, origin/main, origin/HEAD)
Author: lllyasviel <19834515+lllyasviel@users.noreply.github.com>
Date:   Wed Nov 27 17:33:18 2024 -0800
```
