### ISSUE TITLE
python gradio_demo.py How to solve compatibility problems?

### ISSUE THREAD

**Issue by yitao2020** [lllyasviel/IC-Light#104]
(iclight) D:\IC-Light>python gradio_demo.py
Traceback (most recent call last):
  File "D:\IC-Light\gradio_demo.py", line 10, in <module>
    from diffusers import StableDiffusionPipeline, StableDiffusionImg2ImgPipeline
  File "C:\Users\WIN10\.conda\envs\iclight\lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "C:\Users\WIN10\.conda\envs\iclight\lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "C:\Users\WIN10\.conda\envs\iclight\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\Users\WIN10\.conda\envs\iclight\lib\site-packages\huggingface_hub\__init__.py)

(iclight) D:\IC-Light>where python
C:\Users\WIN10\.conda\envs\iclight\python.exe
D:\ProgramData\anaconda3\python.exe
C:\Users\WIN10\AppData\Local\Programs\Python\Python310\python.exe
C:\Users\WIN10\AppData\Local\Programs\Python\Python313\python.exe
C:\Users\WIN10\AppData\Local\Microsoft\WindowsApps\python.exe

**Comment by Ted-cuchuan** [comment]
i also encounter this problem, do you know how to solve this right now? I even try to run this project on google colab, but the error message is the same.

**Comment by yitao2020** [comment]
> 我也遇到了这个问题，你知道现在怎么解决这个问题吗？我甚至尝试在 google colab 上运行这个项目，但错误消息是一样的。



> 'cached_download' from 'huggingface_hub'

What a pain in the ass. I searched carefully for the problem last night and found that the 'cached_download' import command was removed from huggingface_hub 0.26.0. You can only downgrade and manually install huggingface_hub 0.25.0. The downgraded version can start normally, and it must be shut down. for the agent to function properly.

**Comment by yitao2020** [comment]
> i also encounter this problem, do you know how to solve this right now? I even try to run this project on google colab, but the error message is the same.

What a pain in the ass. I searched carefully for the problem last night and found that the 'cached_download' import command was removed from huggingface_hub 0.26.0. You can only downgrade and manually install huggingface_hub 0.25.0. The downgraded version can start normally, and it must be shut down. for the agent to function properly.

**Comment by yitao2020** [comment]
> Well received. Thanks you so much!!! I try the method and i can initiate the model now. But once i upload a picutre, i run the gradio, the gradio just show a error without any further message. The screen capture i attached. Did you run this model successfully on your local device? I am still trying, hope you can help me solve that. ![10f0970785aae1ed43cbd6af44ebe2a](https://private-user-images.githubusercontent.com/115217682/386835618-4519f7ce-a116-41ce-80bd-a3dadfb6f76f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MDc1MTYsIm5iZiI6MTczMTgwNzIxNiwicGF0aCI6Ii8xMTUyMTc2ODIvMzg2ODM1NjE4LTQ1MTlmN2NlLWExMTYtNDFjZS04MGJkLWEzZGFkZmI2Zjc2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QwMTMzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjBmMWEwYjExY2NkNTU5ZTEwZjZlYjUyODE0Zjc0MzY1ZjBjNTU3NDdhNDkwNTlmZTFiMTZkOWVjM2MxNzBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XvNjaxojntMjJTPNYFBMSHx9odngWkLkMdERY8Wc1cE)
> 
> > > i also encounter this problem, do you know how to solve this right now? I even try to run this project on google colab, but the error message is the same.
> > 
> > 
> > What a pain in the ass. I searched carefully for the problem last night and found that the 'cached_download' import command was removed from huggingface_hub 0.26.0. You can only downgrade and manually install huggingface_hub 0.25.0. The downgraded version can start normally, and it must be shut down. for the agent to function properly.

Having the same problems, I don't have that much time to solve them. I went to Bilibili to search and there are many integration packages available for download. I suggest you go there and take a look.

**Comment by tangjm24** [comment]
change `from huggingface_hub import cached_download, hf_hub_download, model_info` to `from huggingface_hub import hf_hub_download, model_info` helps for me

**Comment by MADM1k33** [comment]
Type this, after activating conda env - pip install gradio=3.48.0

**Comment by jhartquist** [comment]
this is what worked for me
```
pip install -U diffusers transformers
```

**Comment by pj263** [comment]
> change `from huggingface_hub import cached_download, hf_hub_download, model_info` to `from huggingface_hub import hf_hub_download, model_info` helps for me

Tried this, still getting the same error. Any other ideas that worked for you?

**Comment by jhartquist** [comment]
> > change `from huggingface_hub import cached_download, hf_hub_download, model_info` to `from huggingface_hub import hf_hub_download, model_info` helps for me
> 
> Tried this, still getting the same error. Any other ideas that worked for you?

Updating to the latest `diffusers` and `transformers` fixed this particular issue for me 

```
pip install -U diffusers transformers
```

**Comment by Vana2793** [comment]
This:

> Updating to the latest `diffusers` and `transformers` fixed this particular issue for me
> 
> ```
> pip install -U diffusers transformers

And

This:

> Type this, after activating conda env - pip install gradio=3.48.0

> ```
> pip install gradio==3.48.0 

For those who don't code and follow exactly what others write like my butt does.


Solved all the issues I was having
Both the ImportError: cannot import name 'cached_download' from 'huggingface_hub
And also just no error message, but error on the webui and nothing working.
