### ISSUE TITLE
Error:expecting value:line 1 column 1(char0)

### ISSUE THREAD

**Issue by sekiro123205** [lllyasviel/IC-Light#105]
![error](https://github.com/user-attachments/assets/9fae833e-dead-4231-8ec9-9370ec9c8d19)
Why do I have this problem and how do I solve it

**Comment by sekiro123205** [comment]
OK，I figured out the problem and get the solution. Just do not run the gradio_demo.py with a proxy

**Comment by Ted-cuchuan** [comment]
Hi, i would like to ask how you successfully run this project. I encounter some problem rigth after i setup the environment and run gradio_demo.py, the error message: "
Traceback (most recent call last):
  File "D:\Github\IC-Light\gradio_demo.py", line 10, in <module>
    from diffusers import StableDiffusionPipeline, StableDiffusionImg2ImgPipeline
  File "D:\CodeTools\Anaconda\envs\iclight\lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "D:\CodeTools\Anaconda\envs\iclight\lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "D:\CodeTools\Anaconda\envs\iclight\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (D:\CodeTools\Anaconda\envs\iclight\lib\site-packages\huggingface_hub\__init__.py)
"
