### ISSUE TITLE
Error loading shm.dll, The specified module could not be found.

### ISSUE THREAD

**Issue by 20222023** [lllyasviel/IC-Light#41]
(cuda) C:\Users\palam\OneDrive\Desktop\IC light\IC-Light>python gradio_demo.py
Traceback (most recent call last):
  File "C:\Users\palam\OneDrive\Desktop\IC light\IC-Light\gradio_demo.py", line 5, in <module>
    import torch
  File "C:\Users\palam\AppData\Roaming\Python\Python310\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\palam\AppData\Roaming\Python\Python310\site-packages\torch\lib\shm.dll" or one of its dependencies

**Comment by eigen2017** [comment]
+1
